<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class CatMarcasSeeder extends Seeder
{
    public function run()
    {
        //Limpieza segura en Postgres evitando bloqueos por FK
        DB::statement('TRUNCATE TABLE cat_marcas CASCADE;');

        // Inserción masiva de tu catálogo real actualizado
        DB::table('cat_marcas')->insert([
            ['id' => 1, 'nombre' => 'Samsung', 'descripcion' => 'Tecnología y electrodomésticos', 'tipo' => 'Electrónica', 'fecha_registro' => '2026-03-16 11:14:31'],
            ['id' => 2, 'nombre' => 'Nike', 'descripcion' => 'Ropa y calzado deportivo', 'tipo' => 'Deportes', 'fecha_registro' => '2026-03-16 11:14:31'],
            ['id' => 3, 'nombre' => 'LG', 'descripcion' => 'Electrónica y línea blanca', 'tipo' => 'Pantallas', 'fecha_registro' => '2026-03-16 11:14:31'],
            ['id' => 4, 'nombre' => 'Adidas', 'descripcion' => 'Moda deportiva', 'tipo' => 'Deportes', 'fecha_registro' => '2026-03-16 11:14:31'],
            ['id' => 5, 'nombre' => 'Whirlpool', 'descripcion' => 'Electrodomésticos de cocina', 'tipo' => 'Hogar', 'fecha_registro' => '2026-03-16 11:14:31'],
            ['id' => 6, 'nombre' => 'Sony', 'descripcion' => 'Tecnología y entretenimiento', 'tipo' => 'Audio', 'fecha_registro' => '2026-03-16 11:14:31'],
            ['id' => 7, 'nombre' => 'Panasonic', 'descripcion' => 'Electrónica y línea blanca', 'tipo' => 'Hogar', 'fecha_registro' => '2026-03-16 11:14:31'],
            ['id' => 8, 'nombre' => 'Puma', 'descripcion' => 'Ropa y accesorios deportivos', 'tipo' => 'Moda', 'fecha_registro' => '2026-03-16 11:14:31'],
            ['id' => 9, 'nombre' => 'Electrolux', 'descripcion' => 'Electrodomésticos premium', 'tipo' => 'Hogar', 'fecha_registro' => '2026-03-16 11:14:31'],
            ['id' => 10, 'nombre' => 'Reebok', 'descripcion' => 'Calzado y ropa deportiva', 'tipo' => 'Deportes', 'fecha_registro' => '2026-03-16 11:14:31'],
            ['id' => 11, 'nombre' => 'Herdez', 'descripcion' => 'Expendedora agricola', 'tipo' => 'Verduras', 'fecha_registro' => '2026-05-23 11:05:58'],
            ['id' => 12, 'nombre' => 'Nike', 'descripcion' => 'Ropa deportiva', 'tipo' => 'Deportiva', 'fecha_registro' => '2026-06-08 21:25:37'],
            ['id' => 13, 'nombre' => 'Adidas', 'descripcion' => 'Ropa y accesorios deportivos', 'tipo' => 'Deportiva', 'fecha_registro' => '2026-06-08 21:25:37'],
            ['id' => 14, 'nombre' => 'Puma', 'descripcion' => 'Moda deportiva y casual', 'tipo' => 'Deportiva', 'fecha_registro' => '2026-06-08 21:25:37'],
            ['id' => 15, 'nombre' => 'Under Armour', 'descripcion' => 'Ropa de entrenamiento', 'tipo' => 'Deportiva', 'fecha_registro' => '2026-06-08 21:25:37'],
            ['id' => 16, 'nombre' => 'Levis', 'descripcion' => 'Jeans y ropa casual', 'tipo' => 'Casual', 'fecha_registro' => '2026-06-08 21:25:37'],
            ['id' => 17, 'nombre' => 'Zara', 'descripcion' => 'Moda contemporánea', 'tipo' => 'Moda', 'fecha_registro' => '2026-06-08 21:25:37'],
            ['id' => 18, 'nombre' => 'H&M', 'descripcion' => 'Ropa para toda la familia', 'tipo' => 'Moda', 'fecha_registro' => '2026-06-08 21:25:37'],
            ['id' => 19, 'nombre' => 'Tommy Hilfiger', 'descripcion' => 'Moda premium casual', 'tipo' => 'Premium', 'fecha_registro' => '2026-06-08 21:25:37'],
            ['id' => 20, 'nombre' => 'Calvin Klein', 'descripcion' => 'Ropa y accesorios', 'tipo' => 'Premium', 'fecha_registro' => '2026-06-08 21:25:37'],
            ['id' => 21, 'nombre' => 'Lacoste', 'descripcion' => 'Ropa casual y deportiva', 'tipo' => 'Casual', 'fecha_registro' => '2026-06-08 21:25:37'],
            ['id' => 22, 'nombre' => 'Campo Verde', 'descripcion' => 'Productor de frutas y verduras frescas', 'tipo' => 'Agrícola', 'fecha_registro' => '2026-06-08 21:26:58'],
            ['id' => 23, 'nombre' => 'Huerta del Sol', 'descripcion' => 'Frutas de temporada', 'tipo' => 'Agrícola', 'fecha_registro' => '2026-06-08 21:26:58'],
            ['id' => 24, 'nombre' => 'Fresh Garden', 'descripcion' => 'Verduras seleccionadas', 'tipo' => 'Agrícola', 'fecha_registro' => '2026-06-08 21:26:58'],
            ['id' => 25, 'nombre' => 'Valle Fresco', 'descripcion' => 'Productos hortofrutícolas', 'tipo' => 'Agrícola', 'fecha_registro' => '2026-06-08 21:26:58'],
            ['id' => 26, 'nombre' => 'La Cosecha', 'descripcion' => 'Frutas y vegetales premium', 'tipo' => 'Agrícola', 'fecha_registro' => '2026-06-08 21:26:58'],
            ['id' => 27, 'nombre' => 'Naturcampo', 'descripcion' => 'Productos agrícolas naturales', 'tipo' => 'Orgánico', 'fecha_registro' => '2026-06-08 21:26:58'],
            ['id' => 28, 'nombre' => 'Del Huerto', 'descripcion' => 'Verduras frescas de cultivo local', 'tipo' => 'Agrícola', 'fecha_registro' => '2026-06-08 21:26:58'],
            ['id' => 29, 'nombre' => 'EcoFrut', 'descripcion' => 'Frutas orgánicas certificadas', 'tipo' => 'Orgánico', 'fecha_registro' => '2026-06-08 21:26:58'],
            ['id' => 30, 'nombre' => 'AgroFresh', 'descripcion' => 'Distribuidor de frutas y verduras', 'tipo' => 'Distribución', 'fecha_registro' => '2026-06-08 21:26:58'],
            ['id' => 31, 'nombre' => 'Tierra Fértil', 'descripcion' => 'Productos frescos del campo', 'tipo' => 'Agrícola', 'fecha_registro' => '2026-06-08 21:26:58'],
            ['id' => 32, 'nombre' => 'Style Accents', 'descripcion' => 'Accesorios de moda para dama y caballero', 'tipo' => 'Accesorios', 'fecha_registro' => '2026-06-08 21:28:16'],
            ['id' => 33, 'nombre' => 'Urban Trends', 'descripcion' => 'Accesorios modernos y casuales', 'tipo' => 'Accesorios', 'fecha_registro' => '2026-06-08 21:28:16'],
            ['id' => 34, 'nombre' => 'Golden Touch', 'descripcion' => 'Joyería y accesorios elegantes', 'tipo' => 'Accesorios', 'fecha_registro' => '2026-06-08 21:28:16'],
            ['id' => 35, 'nombre' => 'Classic Wear', 'descripcion' => 'Accesorios clásicos para vestir', 'tipo' => 'Accesorios', 'fecha_registro' => '2026-06-08 21:28:16'],
            ['id' => 36, 'nombre' => 'Elite Accessories', 'descripcion' => 'Accesorios premium', 'tipo' => 'Accesorios', 'fecha_registro' => '2026-06-08 21:28:16'],
            ['id' => 37, 'nombre' => 'Fashion Point', 'descripcion' => 'Complementos para toda ocasión', 'tipo' => 'Accesorios', 'fecha_registro' => '2026-06-08 21:28:16'],
            ['id' => 38, 'nombre' => 'Trendy Collection', 'descripcion' => 'Accesorios juveniles', 'tipo' => 'Accesorios', 'fecha_registro' => '2026-06-08 21:28:16'],
            ['id' => 39, 'nombre' => 'Silver Line', 'descripcion' => 'Bisutería y accesorios de moda', 'tipo' => 'Accesorios', 'fecha_registro' => '2026-06-08 21:28:16'],
            ['id' => 40, 'nombre' => 'Urban Style', 'descripcion' => 'Accesorios urbanos y contemporáneos', 'tipo' => 'Accesorios', 'fecha_registro' => '2026-06-08 21:28:16'],
            ['id' => 41, 'nombre' => 'Luxury Detail', 'descripcion' => 'Accesorios exclusivos', 'tipo' => 'Accesorios', 'fecha_registro' => '2026-06-08 21:28:16'],
            ['id' => 42, 'nombre' => 'ToyLand', 'descripcion' => 'Juguetes educativos', 'tipo' => 'Juguetes', 'fecha_registro' => '2026-06-08 21:30:21'],
            ['id' => 43, 'nombre' => 'FunKids', 'descripcion' => 'Juguetes para niños', 'tipo' => 'Juguetes', 'fecha_registro' => '2026-06-08 21:30:21'],
            ['id' => 44, 'nombre' => 'Happy Play', 'descripcion' => 'Juguetes recreativos', 'tipo' => 'Juguetes', 'fecha_registro' => '2026-06-08 21:30:21'],
            ['id' => 45, 'nombre' => 'Mega Toys', 'descripcion' => 'Juguetes de colección', 'tipo' => 'Juguetes', 'fecha_registro' => '2026-06-08 21:30:21'],
            ['id' => 46, 'nombre' => 'Play World', 'descripcion' => 'Juguetes infantiles', 'tipo' => 'Juguetes', 'fecha_registro' => '2026-06-08 21:30:21'],
            ['id' => 47, 'nombre' => 'Dream Toys', 'descripcion' => 'Juguetes creativos', 'tipo' => 'Juguetes', 'fecha_registro' => '2026-06-08 21:30:21'],
            ['id' => 48, 'nombre' => 'Kids Factory', 'descripcion' => 'Juguetes didácticos', 'tipo' => 'Juguetes', 'fecha_registro' => '2026-06-08 21:30:21'],
            ['id' => 49, 'nombre' => 'Magic Fun', 'descripcion' => 'Juegos y entertainment', 'tipo' => 'Juguetes', 'fecha_registro' => '2026-06-08 21:30:21'],
            ['id' => 50, 'nombre' => 'Toy Planet', 'descripcion' => 'Juguetes modernos', 'tipo' => 'Juguetes', 'fecha_registro' => '2026-06-08 21:30:21'],
            ['id' => 51, 'nombre' => 'Fun House', 'descripcion' => 'Juguetes para todas las edades', 'tipo' => 'Juguetes', 'fecha_registro' => '2026-06-08 21:30:21'],
            ['id' => 52, 'nombre' => 'Office Pro', 'descripcion' => 'Artículos de oficina', 'tipo' => 'Oficina', 'fecha_registro' => '2026-06-08 21:30:21'],
            ['id' => 53, 'nombre' => 'Work Space', 'descripcion' => 'Suministros empresariales', 'tipo' => 'Oficina', 'fecha_registro' => '2026-06-08 21:30:21'],
            ['id' => 54, 'nombre' => 'Paper Plus', 'descripcion' => 'Papelería y oficina', 'tipo' => 'Oficina', 'fecha_registro' => '2026-06-08 21:30:21'],
            ['id' => 55, 'nombre' => 'Desk Solutions', 'descripcion' => 'Accesorios de oficina', 'tipo' => 'Oficina', 'fecha_registro' => '2026-06-08 21:30:21'],
            ['id' => 56, 'nombre' => 'Office Max', 'descripcion' => 'Equipamiento de oficina', 'tipo' => 'Oficina', 'fecha_registro' => '2026-06-08 21:30:21'],
            ['id' => 57, 'nombre' => 'Business Line', 'descripcion' => 'Productos corporativos', 'tipo' => 'Oficina', 'fecha_registro' => '2026-06-08 21:30:21'],
            ['id' => 58, 'nombre' => 'Smart Office', 'descripcion' => 'Soluciones administrativas', 'tipo' => 'Oficina', 'fecha_registro' => '2026-06-08 21:30:21'],
            ['id' => 59, 'nombre' => 'Pro Desk', 'descripcion' => 'Mobiliario y oficina', 'tipo' => 'Oficina', 'fecha_registro' => '2026-06-08 21:30:21'],
            ['id' => 60, 'nombre' => 'Office Zone', 'descripcion' => 'Papelería profesional', 'tipo' => 'Oficina', 'fecha_registro' => '2026-06-08 21:30:21'],
            ['id' => 61, 'nombre' => 'Executive Supply', 'descripcion' => 'Suministros ejecutivos', 'tipo' => 'Oficina', 'fecha_registro' => '2026-06-08 21:30:21'],
            ['id' => 62, 'nombre' => 'TechVision', 'descripcion' => 'Dispositivos electrónicos', 'tipo' => 'Electrónica', 'fecha_registro' => '2026-06-08 21:30:21'],
            ['id' => 63, 'nombre' => 'Digital World', 'descripcion' => 'Tecnología y accesorios', 'tipo' => 'Electrónica', 'fecha_registro' => '2026-06-08 21:30:21'],
            ['id' => 64, 'nombre' => 'Smart Tech', 'descripcion' => 'Equipos inteligentes', 'tipo' => 'Electrónica', 'fecha_registro' => '2026-06-08 21:30:21'],
            ['id' => 65, 'nombre' => 'ElectroMax', 'descripcion' => 'Electrónica de consumo', 'tipo' => 'Electrónica', 'fecha_registro' => '2026-06-08 21:30:21'],
            ['id' => 66, 'nombre' => 'NextGen', 'descripcion' => 'Tecnología innovadora', 'tipo' => 'Electrónica', 'fecha_registro' => '2026-06-08 21:30:21'],
            ['id' => 67, 'nombre' => 'TechPro', 'descripcion' => 'Accesorios tecnológicos', 'tipo' => 'Electrónica', 'fecha_registro' => '2026-06-08 21:30:21'],
            ['id' => 68, 'nombre' => 'Power Digital', 'descripcion' => 'Equipos electrónicos', 'tipo' => 'Electrónica', 'fecha_registro' => '2026-06-08 21:30:21'],
            ['id' => 69, 'nombre' => 'Future Electronics', 'descripcion' => 'Soluciones digitales', 'tipo' => 'Electrónica', 'fecha_registro' => '2026-06-08 21:30:21'],
            ['id' => 70, 'nombre' => 'Global Tech', 'descripcion' => 'Productos tecnológicos', 'tipo' => 'Electrónica', 'fecha_registro' => '2026-06-08 21:30:21'],
            ['id' => 71, 'nombre' => 'Innovatek', 'descripcion' => 'Innovación electrónica', 'tipo' => 'Electrónica', 'fecha_registro' => '2026-06-08 21:30:21'],
            ['id' => 72, 'nombre' => 'Casa Ideal', 'descripcion' => 'Artículos para el hogar', 'tipo' => 'Hogar', 'fecha_registro' => '2026-06-08 21:30:21'],
            ['id' => 73, 'nombre' => 'Home Style', 'descripcion' => 'Decoración y hogar', 'tipo' => 'Hogar', 'fecha_registro' => '2026-06-08 21:30:21'],
            ['id' => 74, 'nombre' => 'Living Space', 'descripcion' => 'Accesorios domésticos', 'tipo' => 'Hogar', 'fecha_registro' => '2026-06-08 21:30:21'],
            ['id' => 75, 'nombre' => 'Mi Hogar', 'descripcion' => 'Productos para casa', 'tipo' => 'Hogar', 'fecha_registro' => '2026-06-08 21:30:21'],
            ['id' => 76, 'nombre' => 'Home Comfort', 'descripcion' => 'Comodidad para el hogar', 'tipo' => 'Hogar', 'fecha_registro' => '2026-06-08 21:30:21'],
            ['id' => 77, 'nombre' => 'Casa Moderna', 'descripcion' => 'Decoración contemporánea', 'tipo' => 'Hogar', 'fecha_registro' => '2026-06-08 21:30:21'],
            ['id' => 78, 'nombre' => 'Hogar Plus', 'descripcion' => 'Soluciones domésticas', 'tipo' => 'Hogar', 'fecha_registro' => '2026-06-08 21:30:21'],
            ['id' => 79, 'nombre' => 'Ambiente Perfecto', 'descripcion' => 'Decoración interior', 'tipo' => 'Hogar', 'fecha_registro' => '2026-06-08 21:30:21'],
            ['id' => 80, 'nombre' => 'Home Collection', 'descripcion' => 'Colección para el hogar', 'tipo' => 'Hogar', 'fecha_registro' => '2026-06-08 21:30:21'],
            ['id' => 81, 'nombre' => 'Eco Home', 'descripcion' => 'Productos ecológicos', 'tipo' => 'Hogar', 'fecha_registro' => '2026-06-08 21:30:21'],
            ['id' => 82, 'nombre' => 'Pet Care', 'descripcion' => 'Productos para mascotas', 'tipo' => 'Mascotas', 'fecha_registro' => '2026-06-08 21:30:21'],
            ['id' => 83, 'nombre' => 'Happy Pets', 'descripcion' => 'Accesorios para mascotas', 'tipo' => 'Mascotas', 'fecha_registro' => '2026-06-08 21:30:21'],
            ['id' => 84, 'nombre' => 'Pet World', 'descripcion' => 'Alimentos y accesorios', 'tipo' => 'Mascotas', 'fecha_registro' => '2026-06-08 21:30:21'],
            ['id' => 85, 'nombre' => 'Animal Friends', 'descripcion' => 'Cuidado animal', 'tipo' => 'Mascotas', 'fecha_registro' => '2026-06-08 21:30:21'],
            ['id' => 86, 'nombre' => 'Pet House', 'descripcion' => 'Bienestar para mascotas', 'tipo' => 'Mascotas', 'fecha_registro' => '2026-06-08 21:30:21'],
            ['id' => 87, 'nombre' => 'Mascota Feliz', 'descripcion' => 'Productos veterinarios', 'tipo' => 'Mascotas', 'fecha_registro' => '2026-06-08 21:30:21'],
            ['id' => 88, 'nombre' => 'Pet Life', 'descripcion' => 'Accesorios premium', 'tipo' => 'Mascotas', 'fecha_registro' => '2026-06-08 21:30:21'],
            ['id' => 89, 'nombre' => 'Dog & Cat', 'descripcion' => 'Especialistas en mascotas', 'tipo' => 'Mascotas', 'fecha_registro' => '2026-06-08 21:30:21'],
            ['id' => 90, 'nombre' => 'Pet Family', 'descripcion' => 'Artículos para mascotas', 'tipo' => 'Mascotas', 'fecha_registro' => '2026-06-08 21:30:21'],
            ['id' => 91, 'nombre' => 'Natural Pets', 'descripcion' => 'Productos naturales', 'tipo' => 'Mascotas', 'fecha_registro' => '2026-06-08 21:30:21'],
            ['id' => 92, 'nombre' => 'Pan del Día', 'descripcion' => 'Productos de panadería', 'tipo' => 'Panadería', 'fecha_registro' => '2026-06-08 21:30:21'],
            ['id' => 93, 'nombre' => 'La Espiga', 'descripcion' => 'Pan artesanal', 'tipo' => 'Panadería', 'fecha_registro' => '2026-06-08 21:30:21'],
            ['id' => 94, 'nombre' => 'Horno Real', 'descripcion' => 'Pan fresco diario', 'tipo' => 'Panadería', 'fecha_registro' => '2026-06-08 21:30:21'],
            ['id' => 95, 'nombre' => 'Dulce Aroma', 'descripcion' => 'Pan y repostería', 'tipo' => 'Panadería', 'fecha_registro' => '2026-06-08 21:30:21'],
            ['id' => 96, 'nombre' => 'Pan Selecto', 'descripcion' => 'Pan gourmet', 'tipo' => 'Panadería', 'fecha_registro' => '2026-06-08 21:30:21'],
            ['id' => 97, 'nombre' => 'Tradición Panadera', 'descripcion' => 'Pan tradicional', 'tipo' => 'Panadería', 'fecha_registro' => '2026-06-08 21:30:21'],
            ['id' => 98, 'nombre' => 'Golden Bread', 'descripcion' => 'Especialidades horneadas', 'tipo' => 'Panadería', 'fecha_registro' => '2026-06-08 21:30:21'],
            ['id' => 99, 'nombre' => 'Pan Casero', 'descripcion' => 'Pan artesanal fresco', 'tipo' => 'Panadería', 'fecha_registro' => '2026-06-08 21:30:21'],
            ['id' => 100, 'nombre' => 'El Trigal', 'descripcion' => 'Productos horneados', 'tipo' => 'Panadería', 'fecha_registro' => '2026-06-08 21:30:21'],
            ['id' => 101, 'nombre' => 'Sabor a Horno', 'descripcion' => 'Panadería premium', 'tipo' => 'Panadería', 'fecha_registro' => '2026-06-08 21:30:21'],
            ['id' => 102, 'nombre' => 'Health Plus', 'descripcion' => 'Productos para la salud', 'tipo' => 'Salud', 'fecha_registro' => '2026-06-08 21:30:21'],
            ['id' => 103, 'nombre' => 'Vida Sana', 'descripcion' => 'Bienestar integral', 'tipo' => 'Salud', 'fecha_registro' => '2026-06-08 21:30:21'],
            ['id' => 104, 'nombre' => 'NutriCare', 'descripcion' => 'Suplementos y salud', 'tipo' => 'Salud', 'fecha_registro' => '2026-06-08 21:30:21'],
            ['id' => 105, 'nombre' => 'Wellness Pro', 'descripcion' => 'Productos de bienestar', 'tipo' => 'Salud', 'fecha_registro' => '2026-06-08 21:30:21'],
            ['id' => 106, 'nombre' => 'Natural Health', 'descripcion' => 'Salud natural', 'tipo' => 'Salud', 'fecha_registro' => '2026-06-08 21:30:21'],
            ['id' => 107, 'nombre' => 'BioCare', 'descripcion' => 'Cuidado personal', 'tipo' => 'Salud', 'fecha_registro' => '2026-06-08 21:30:21'],
            ['id' => 108, 'nombre' => 'Vital Life', 'descripcion' => 'Productos saludables', 'tipo' => 'Salud', 'fecha_registro' => '2026-06-08 21:30:21'],
            ['id' => 109, 'nombre' => 'Healthy Choice', 'descripcion' => 'Opciones para el bienestar', 'tipo' => 'Salud', 'fecha_registro' => '2026-06-08 21:30:21'],
            ['id' => 110, 'nombre' => 'Salud Integral', 'descripcion' => 'Artículos de cuidado', 'tipo' => 'Salud', 'fecha_registro' => '2026-06-08 21:30:21'],
            ['id' => 111, 'nombre' => 'Life Balance', 'descripcion' => 'Bienestar y salud', 'tipo' => 'Salud', 'fecha_registro' => '2026-06-08 21:30:21'],
        ]);

        //Al meter IDs fijos, resincronizamos la secuencia del autoincrementable de Postgres
        DB::statement("SELECT setval(pg_get_serial_sequence('cat_marcas', 'id'), coalesce(max(id), 1), max(id) IS NOT null) FROM cat_marcas;");
    }
}
