<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class StockSeeder extends Seeder
{
    public function run(): void
    {
        DB::table('stock')->insert([
            [
                'id' => 1,
                'producto_id' => 1,
                'cantidad' => 40,
                'ubicacion' => 'Ciudad de Mexico',
                'estado' => 'disponible',
                'minimo_seguro' => 100,
                'maximo_permitido' => 500,
                'fecha_ingreso' => '2025-11-14 00:00:00',
                'fecha_vencimiento' => '2025-11-21',
                'lote' => '',
                'observaciones' => 'Sandia mx',
                'activo' => true,
                'tipo_movimiento' => 'entrada',
                'usuario_id' => null,
                'created_at' => '2025-11-14 17:30:21.503',
                'updated_at' => '2025-11-14 17:30:21.503',
                'id_lote' => 1
            ],
            [
                'id' => 2,
                'producto_id' => 2,
                'cantidad' => 20,
                'ubicacion' => 'Ciudad de México',
                'estado' => 'disponible',
                'minimo_seguro' => 10,
                'maximo_permitido' => 40,
                'fecha_ingreso' => '2025-11-14 00:00:00',
                'fecha_vencimiento' => '2025-11-14',
                'lote' => '',
                'observaciones' => 'Uva verde',
                'activo' => true,
                'tipo_movimiento' => 'entrada',
                'usuario_id' => null,
                'created_at' => '2025-11-14 17:32:08.614',
                'updated_at' => '2025-11-14 17:32:08.614',
                'id_lote' => 1
            ],
            [
                'id' => 3,
                'producto_id' => 3,
                'cantidad' => 100,
                'ubicacion' => 'Ciudad de México',
                'estado' => 'disponible',
                'minimo_seguro' => 10,
                'maximo_permitido' => 200,
                'fecha_ingreso' => '2025-11-14 00:00:00',
                'fecha_vencimiento' => '2025-11-14',
                'lote' => '',
                'observaciones' => 'x',
                'activo' => true,
                'tipo_movimiento' => 'entrada',
                'usuario_id' => null,
                'created_at' => '2025-11-14 17:46:44.901',
                'updated_at' => '2025-11-14 17:46:44.901',
                'id_lote' => 1
            ],
            [
                'id' => 4,
                'producto_id' => 4,
                'cantidad' => 100,
                'ubicacion' => 'Ciudad de México',
                'estado' => 'disponible',
                'minimo_seguro' => 10,
                'maximo_permitido' => 200,
                'fecha_ingreso' => '2025-11-14 00:00:00',
                'fecha_vencimiento' => '2025-11-14',
                'lote' => '',
                'observaciones' => 'x',
                'activo' => true,
                'tipo_movimiento' => 'entrada',
                'usuario_id' => null,
                'created_at' => '2025-11-14 17:46:44.901',
                'updated_at' => '2025-11-14 17:46:44.901',
                'id_lote' => 1
            ],
            [
                'id' => 5,
                'producto_id' => 5,
                'cantidad' => 100,
                'ubicacion' => 'Ciudad de México',
                'estado' => 'disponible',
                'minimo_seguro' => 10,
                'maximo_permitido' => 200,
                'fecha_ingreso' => '2025-11-14 00:00:00',
                'fecha_vencimiento' => '2025-11-14',
                'lote' => '',
                'observaciones' => 'x',
                'activo' => true,
                'tipo_movimiento' => 'entrada',
                'usuario_id' => null,
                'created_at' => '2025-11-14 17:46:44.901',
                'updated_at' => '2025-11-14 17:46:44.901',
                'id_lote' => 1
            ],
            [
                'id' => 6,
                'producto_id' => 6,
                'cantidad' => 100,
                'ubicacion' => 'Ciudad de México',
                'estado' => 'disponible',
                'minimo_seguro' => 10,
                'maximo_permitido' => 200,
                'fecha_ingreso' => '2025-11-14 00:00:00',
                'fecha_vencimiento' => '2025-11-14',
                'lote' => '',
                'observaciones' => 'x',
                'activo' => true,
                'tipo_movimiento' => 'entrada',
                'usuario_id' => null,
                'created_at' => '2025-11-14 17:46:44.901',
                'updated_at' => '2025-11-14 17:46:44.901',
                'id_lote' => 1
            ],
            [
                'id' => 7,
                'producto_id' => 7,
                'cantidad' => 100,
                'ubicacion' => 'Ciudad de México',
                'estado' => 'disponible',
                'minimo_seguro' => 10,
                'maximo_permitido' => 200,
                'fecha_ingreso' => '2025-11-14 00:00:00',
                'fecha_vencimiento' => '2025-11-14',
                'lote' => '',
                'observaciones' => 'x',
                'activo' => true,
                'tipo_movimiento' => 'entrada',
                'usuario_id' => null,
                'created_at' => '2025-11-14 17:46:44.901',
                'updated_at' => '2025-11-14 17:46:44.901',
                'id_lote' => 1
            ],
            [
                'id' => 8,
                'producto_id' => 8,
                'cantidad' => 100,
                'ubicacion' => 'Ciudad de México',
                'estado' => 'disponible',
                'minimo_seguro' => 10,
                'maximo_permitido' => 200,
                'fecha_ingreso' => '2025-11-14 00:00:00',
                'fecha_vencimiento' => '2025-11-14',
                'lote' => '',
                'observaciones' => 'x',
                'activo' => true,
                'tipo_movimiento' => 'entrada',
                'usuario_id' => null,
                'created_at' => '2025-11-14 17:46:44.901',
                'updated_at' => '2025-11-14 17:46:44.901',
                'id_lote' => 1
            ],
            [
                'id' => 9,
                'producto_id' => 9,
                'cantidad' => 100,
                'ubicacion' => 'Ciudad de México',
                'estado' => 'disponible',
                'minimo_seguro' => 10,
                'maximo_permitido' => 200,
                'fecha_ingreso' => '2025-11-14 00:00:00',
                'fecha_vencimiento' => '2025-11-14',
                'lote' => '',
                'observaciones' => 'x',
                'activo' => true,
                'tipo_movimiento' => 'entrada',
                'usuario_id' => null,
                'created_at' => '2025-11-14 17:46:44.901',
                'updated_at' => '2025-11-14 17:46:44.901',
                'id_lote' => 1
            ],
            [
                'id' => 10,
                'producto_id' => 10,
                'cantidad' => 100,
                'ubicacion' => 'Ciudad de México',
                'estado' => 'disponible',
                'minimo_seguro' => 10,
                'maximo_permitido' => 200,
                'fecha_ingreso' => '2025-11-14 00:00:00',
                'fecha_vencimiento' => '2025-11-14',
                'lote' => '',
                'observaciones' => 'x',
                'activo' => true,
                'tipo_movimiento' => 'entrada',
                'usuario_id' => null,
                'created_at' => '2025-11-14 17:46:44.901',
                'updated_at' => '2025-11-14 17:46:44.901',
                'id_lote' => 1
            ],
            [
                'id' => 11,
                'producto_id' => 11,
                'cantidad' => 100,
                'ubicacion' => 'Ciudad de México',
                'estado' => 'disponible',
                'minimo_seguro' => 10,
                'maximo_permitido' => 200,
                'fecha_ingreso' => '2025-11-14 00:00:00',
                'fecha_vencimiento' => '2025-11-14',
                'lote' => '',
                'observaciones' => 'x',
                'activo' => true,
                'tipo_movimiento' => 'entrada',
                'usuario_id' => null,
                'created_at' => '2025-11-14 17:46:44.901',
                'updated_at' => '2025-11-14 17:46:44.901',
                'id_lote' => 4
            ],
            [
                'id' => 12,
                'producto_id' => 12,
                'cantidad' => 100,
                'ubicacion' => 'Ciudad de México',
                'estado' => 'disponible',
                'minimo_seguro' => 10,
                'maximo_permitido' => 200,
                'fecha_ingreso' => '2025-11-14 00:00:00',
                'fecha_vencimiento' => '2025-11-14',
                'lote' => '',
                'observaciones' => 'x',
                'activo' => true,
                'tipo_movimiento' => 'entrada',
                'usuario_id' => null,
                'created_at' => '2025-11-14 17:46:44.901',
                'updated_at' => '2025-11-14 17:46:44.901',
                'id_lote' => 4
            ],
            [
                'id' => 13,
                'producto_id' => 13,
                'cantidad' => 100,
                'ubicacion' => 'Ciudad de México',
                'estado' => 'disponible',
                'minimo_seguro' => 10,
                'maximo_permitido' => 200,
                'fecha_ingreso' => '2025-11-14 00:00:00',
                'fecha_vencimiento' => '2025-11-14',
                'lote' => '',
                'observaciones' => 'x',
                'activo' => true,
                'tipo_movimiento' => 'entrada',
                'usuario_id' => null,
                'created_at' => '2025-11-14 17:46:44.901',
                'updated_at' => '2025-11-14 17:46:44.901',
                'id_lote' => 4
            ],
            [
                'id' => 14,
                'producto_id' => 14,
                'cantidad' => 100,
                'ubicacion' => 'Ciudad de México',
                'estado' => 'disponible',
                'minimo_seguro' => 10,
                'maximo_permitido' => 200,
                'fecha_ingreso' => '2025-11-14 00:00:00',
                'fecha_vencimiento' => '2025-11-14',
                'lote' => '',
                'observaciones' => 'x',
                'activo' => true,
                'tipo_movimiento' => 'entrada',
                'usuario_id' => null,
                'created_at' => '2025-11-14 17:46:44.901',
                'updated_at' => '2025-11-14 17:46:44.901',
                'id_lote' => 4
            ],
            [
                'id' => 15,
                'producto_id' => 15,
                'cantidad' => 100,
                'ubicacion' => 'Ciudad de México',
                'estado' => 'disponible',
                'minimo_seguro' => 10,
                'maximo_permitido' => 200,
                'fecha_ingreso' => '2025-11-14 00:00:00',
                'fecha_vencimiento' => '2025-11-14',
                'lote' => '',
                'observaciones' => 'x',
                'activo' => true,
                'tipo_movimiento' => 'entrada',
                'usuario_id' => null,
                'created_at' => '2025-11-14 17:46:44.901',
                'updated_at' => '2025-11-14 17:46:44.901',
                'id_lote' => 4
            ],
            [
                'id' => 16,
                'producto_id' => 16,
                'cantidad' => 100,
                'ubicacion' => 'Ciudad de México',
                'estado' => 'disponible',
                'minimo_seguro' => 10,
                'maximo_permitido' => 200,
                'fecha_ingreso' => '2025-11-14 00:00:00',
                'fecha_vencimiento' => '2025-11-14',
                'lote' => '',
                'observaciones' => 'x',
                'activo' => true,
                'tipo_movimiento' => 'entrada',
                'usuario_id' => null,
                'created_at' => '2025-11-14 17:46:44.901',
                'updated_at' => '2025-11-14 17:46:44.901',
                'id_lote' => 4
            ],
            [
                'id' => 17,
                'producto_id' => 17,
                'cantidad' => 100,
                'ubicacion' => 'Ciudad de México',
                'estado' => 'disponible',
                'minimo_seguro' => 10,
                'maximo_permitido' => 200,
                'fecha_ingreso' => '2025-11-14 00:00:00',
                'fecha_vencimiento' => '2025-11-14',
                'lote' => '',
                'observaciones' => 'x',
                'activo' => true,
                'tipo_movimiento' => 'entrada',
                'usuario_id' => null,
                'created_at' => '2025-11-14 17:46:44.901',
                'updated_at' => '2025-11-14 17:46:44.901',
                'id_lote' => 4
            ],
            // Aquí seguirías agregando los demás registros...
        ]);
    }
}
